spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home_app_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  security:
    authenticated: ${SPRING_SECURITY_AUTHENTICATED:true}
    user:
      name: admin
      password: admin

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true